name: dml
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.11
- pytorch=2.3.1
- torchvision=0.18.1
- cpuonly
- pip
- numpy
- jupyter
- matplotlib
- scikit-learn
- scipy
- pandas
- seaborn
- pip:
  - future
  - tb-nightly
  - gymnasium==0.29.1
  - pillow
  - kaggle==1.6.14
  - ipywidgets
  - einops
  - transformers
  - datasets
