name: dml
channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- pip
- numpy
- jupyter
- matplotlib
- scikit-learn
- scipy
- pandas
- seaborn
- pip:
  - future
  - tb-nightly
  - gymnasium==0.29.1
  - pillow
  - kaggle==1.6.14
  - ipywidgets
  - einops
  - transformers
  - datasets
  - --extra-index-url https://download.pytorch.org/whl/cu118
  - torch==2.3.1+cu118
  - torchvision==0.18.1+cu118
